# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.background-update-timer", 1204744277);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1204744277);
user_pref("browser.places.importBookmarksHTML", true);
user_pref("extensions.lastAppVersion", "0.5");
